apiVersion: v1
kind: Service
metadata:
  name: ddac-server
  labels:
    app: ddac-server
spec:
  type: NodePort
  ports:
    - port: 9042
      nodePort: 30042
      protocol: TCP
      name: cql
  selector:
    app: ddac-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ddac-server
  labels:
    app: ddac-server
spec:
  serviceName: ddac-server
  replicas: 1
  selector:
    matchLabels:
      app: ddac-server
  template:
    metadata:
      namespace: datastax
      labels:
        app: ddac-server
    spec:
      terminationGracePeriodSeconds: 1800
      securityContext:
        fsGroup: 1000
      containers:
        - name: ddac-server
          image: datastax/ddac:5.1.15
          imagePullPolicy: Always
          args: []
          ports:
            # NOTE: port declarations here are informational only; all ports are actually open
            # Cassandra Ports
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - nodetool drain
          env:
            - name: DS_LICENSE
              value: accept
            - name: JVM_EXTRA_OPTS
              value: "-Xms1g -Xmx2g"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          # These volume mounts are persistent. They are like inline claims,
          # but not exactly because the names need to match exactly one of
          # the stateful pod volumes.
          volumeMounts:
            - name: dse-data
              mountPath: /var/lib/cassandra
          # readinessProbe:
          #   exec:
          #     command:
          #     - cqlsh
          #   failureThreshold: 20
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
    - metadata:
        name: dse-data
        namespace: datastax
        annotations:
          pv.beta.kubernetes.io/gid: "1000"
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName:
        resources:
          requests:
            storage: 5Gi
            # ---
            # kind: StorageClass
            # apiVersion: storage.k8s.io/v1
            # metadata:
            #   name: fast
            # provisioner: k8s.io/minikube-hostpath
            # parameters:
            #   type: pd-ssd
