image: datastax/dse-studio
env:
  DS_LICENSE: accept
ports:
  - "9091"
containerArgs: ""
healthCheck:
  command: "wget localhost:9091 -q -O - > /dev/null 2>&1"
  interval: 10s
  retries: "20"
  timeout: 10s
