image: datastax/dse-server:6.7.4
env:
  DS_LICENSE: accept
  JVM_EXTRA_OPS: "-Xms1g -Xmx2g"
ports:
  - "9042"
  - "9077"
  - "9142"
healthCheck:
  command: cqlsh
  interval: 10s
  retries: "20"
  timeout: 10s
